Update docs-update.yml (#79)

diff --git a/.github/workflows/docs-update.yml b/.github/workflows/docs-update.yml
--- a/.github/workflows/docs-update.yml
+++ b/.github/workflows/docs-update.yml
@@ -1,20 +1,16 @@
 name: Update Documentation
 
 on:
-  push:
-    branches:
-      - docs
-    paths:
-      - docs/**
   workflow_dispatch:
 
 jobs:
   docs:
-    uses: codeshelldev/gh-actions/.github/workflows/docs-update.yml@main
-    name: Template Docs
-    with:
-      template-path: docs/
-      output-path: docs/
-      output-branch: docs-build
-    secrets:
-      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Update Documentation
+        if: ${{ github.ref == 'refs/heads/main' }}
+        run: |
+          echo "❌ This workflow cannot be run from the main branch."
+          echo "Please pin to a release, use another branch or commit SHA instead of @main."
+          exit 1
